### ISSUE TITLE
The next release plan?

### ISSUE THREAD

**Issue by ethe** [aio-libs/aiomysql#466]
The latest version has been released on Dec 20, 2018, do you have any plan about the next release?

**Comment by TensorTom** [comment]
There are PRs and fork branches that should probably be merged. Just to get the lib working with python 3.8 I had to use a fork. Super curious about state of dev as well.

**Comment by ethe** [comment]
Exactly, I have to fork this lib and patch some commits which are not be merged.

**Comment by MateuszCzubak** [comment]
This project looks dead

**Comment by webknjaz** [comment]
I don't think that it's worked on actively but if somebody is willing to fix the CI, I think I can release a patch version with that py3.8 fix.

**Comment by rjcortese** [comment]
Any ideas what fixing the CI involves?

**Comment by webknjaz** [comment]
Currently, it fails on some mysql connectivity check. I guess it used to work with some older Travis CI VMs and now it doesn't. There's also some commits here https://github.com/aio-libs/aiomysql/pull/434/files but it's unfinished. Plus need to add Python 3.8 to the matrix finally. I don't have time to dig into it myself but these pointers should be enough to start looking into it.

**Comment by terrycain** [comment]
Tests have been updated, if you get py3.7/py3.8 prs in that pass Travis I'll look into merging and releasing

**Comment by leandroltavares** [comment]
Is there any target date for the next release?

**Comment by MateuszCzubak** [comment]
@terrycain can you please take a look at https://github.com/aio-libs/aiomysql/pull/493/? I have managed to make tests pass for both 3.7 and 3.8

**Comment by MateuszCzubak** [comment]
@terrycain my PR was merged, can you release new version now?

**Comment by MateuszCzubak** [comment]
@jettify maybe you could also help us here?

**Comment by sloev** [comment]
Its inexplicable to me that there has been no new release since 2018.

Especially since this lib is basically the only maintained asyncio mysql implementation. 

I am saying maintained because i can see there is action in this repo, PR's get merged, cleanups, etc. But that all looses value when we all have to build source by git tag instead of relying on a release. 

Can the maintainer of this repo please clear up if he/she/? needs help, more hands on the project? doesnt have time to maintain this? doesnt have intention of pushing releases?

cuz the last release is used by 6200 projects here alone on github so we are quite fragile

**Comment by sloev** [comment]
i can see that @terrycain is busy now so i guess my comments above are more long-term

> "Am busy with a new job but this projects been left for a while. Will have a look this coming week once ive fixed travis
- https://github.com/aio-libs/aiomysql/pull/434#issuecomment-619376593

**Comment by silverwind** [comment]
Looking forward to a new release. Just now I've been facing this issue:

```
ERROR: aiomysql 0.0.20 has requirement PyMySQL<=0.9.2,>=0.9, but you'll have pymysql 0.9.3 which is incompatible.
```

PyMySQL 0.9.2 is completely broken on macOS, it just crashes on startup. It was updated in https://github.com/aio-libs/aiomysql/commit/f9b86aa08576c677afe16caf41aa2ab685b0f995, just needs a release.

**Comment by webknjaz** [comment]
Folks, it looks like there's following maintenance activities necessary before making the release (unless I'm missing something):

1) Check https://github.com/aio-libs/aiomysql/compare/v0.0.20...master and compose a changelog based on it
2) Figure out if there's any breaking changes and decide if the release would need a minor version bump or patch, or maybe major
3) Cut a tag and push it in the repo, this would trigger the fully automatic release pipeline

While I technically have the absolute power over this org, I cannot do this because I'm not really involved in the development of this library and I may be missing some context that the maintainers have.

Though, if somebody does perform these activities **and** convinces @terrycain or @jettify give it a green light, I could push the tag effectively cutting the release.

On a side note, it seems like this project would benefit from having more active maintainers but again, unless somebody has a blessing of @terrycain / @jettify, I won't be able to add new faces. If somebody 
"wants in", make sure to collect their :+1:s.

**Comment by sloev** [comment]
i didnt have time to wait for this so i wrapped this small class up which uses an async interface to a threaded sqlalchemy pool:
https://gist.github.com/sloev/20a421b9c8084d02b9a379b5d69a61e5
its been in production for some months, no issues

**Comment by fabaff** [comment]
I would like see a new release as well. The Fedora Package is broken now due to the releases pinning.

**Comment by MateuszCzubak** [comment]
@webknjaz It seems that we won't be hearing from @terrycain and @jettify anytime soon. How about releasing a new version with the current state, bumping the minor part (so it could become 0.1.0)? I understand that some things may break but the alternative of not having a release seems much worse to me.

**Comment by and-semakin** [comment]
@webknjaz I've summarized changes that happened after the 0.0.20 release, please check it out at #538. Seems like there are no breaking changes, so I propose the next version to be 0.0.21.

**Comment by and-semakin** [comment]
Woohoo! New release! https://pypi.org/project/aiomysql/ 🎉
